#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");
entry("meminfo");
entry("waitpid");
entry("getnice"); # Generate the user-space syscall stub that triggers ecall for getnice.
entry("setnice"); # Generate the user-space syscall stub that triggers ecall for setnice.
entry("ps"); # Generate the user-space syscall stub that triggers ecall for ps.
entry("mmap");    # Generate the Slide 11 user-space stub that triggers ecall for mmap().
entry("munmap");  # Generate the Slide 26 user-space stub that triggers ecall for munmap().
entry("freemem"); # Generate the Slide 27 user-space stub that triggers ecall for freemem().
